CC ?= cc
CPPFLAGS += -D_POSIX_C_SOURCE=200809L
CFLAGS ?= -std=c17 -Wall -Wextra -Wpedantic
TARGET := {{name}}
SOURCE := alignment.c arena.c files.c string_view.c main.c

.PHONY: build run release debug install clean

build:
	$(CC) $(CPPFLAGS) $(CFLAGS) $(SOURCE) -o $(TARGET)

run: build
	./$(TARGET)

release:
	$(CC) $(CPPFLAGS) $(CFLAGS) -O2 $(SOURCE) -o $(TARGET)

debug:
	$(CC) $(CPPFLAGS) $(CFLAGS) -O0 -g $(SOURCE) -o $(TARGET)

install: release
	mkdir -p ~/.local/bin
	cp $(TARGET) ~/.local/bin/$(TARGET)
	chmod +x ~/.local/bin/$(TARGET)

clean:
	rm -rf $(TARGET) $(TARGET).dSYM/
