.PHONY: check build run release debug install clean

check:
	odin check .

build:
	odin build .

run:
	odin run .

release:
	odin build . -o:speed -microarch:native

debug:
	odin build . -debug

install: release
	mkdir -p ~/.local/bin
	cp {name} ~/.local/bin/{name}
	chmod +x ~/.local/bin/{name}

clean:
	rm -rf {name} {name}.dSYM/
